### ISSUE TITLE
代码运行出错

### ISSUE THREAD

**Issue by huamo555** [xukechun/Vision-Language-Grasping#10]
很抱歉再一次打扰您，我现在尝试运行您的test.py文件，我将下载好的ViT-B-32.pt存放在指定的目录中，代替直接从github上下载它（因为实验室的服务器不能连外网），这样的操作应该可以起到相同的作用吧？
再这样操作之后，后续会出现报错：

Traceback (most recent call last):
  File "train.py", line 93, in <module>
    agent = ViLG(grasp_dim=7, args=args)
  File "/data2/gaoyuming/reforce_project/Vision-Language-Grasping-master/models/sac.py", line 15, in __init__
    self.vilg_fusion = CLIPGraspFusion(grasp_dim, args.width, args.layers, args.heads, self.device).to(device=self.device)
  File "/data2/gaoyuming/reforce_project/Vision-Language-Grasping-master/models/networks.py", line 208, in __init__
    self._load_clip()
  File "/data2/gaoyuming/reforce_project/Vision-Language-Grasping-master/models/networks.py", line 232, in _load_clip
    model, _ = load_clip("ViT-B/32", device=self.device)
  File "/data2/gaoyuming/reforce_project/Vision-Language-Grasping-master/models/core/clip.py", line 570, in load_clip
    model.apply(patch_device)
  File "/data2/gaoyuming/anaconda3/envs/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 473, in apply
    module.apply(fn)
  File "/data2/gaoyuming/anaconda3/envs/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 473, in apply
    module.apply(fn)
  File "/data2/gaoyuming/anaconda3/envs/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 473, in apply
    module.apply(fn)
  [Previous line repeated 3 more times]
  File "/data2/gaoyuming/anaconda3/envs/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 474, in apply
    fn(self)
  File "/data2/gaoyuming/reforce_project/Vision-Language-Grasping-master/models/core/clip.py", line 561, in patch_device
    graphs = [module.graph] if hasattr(module, "graph") else []
  File "/data2/gaoyuming/anaconda3/envs/env/lib/python3.7/site-packages/torch/jit/_script.py", line 449, in graph
    return self._c._get_method("forward").graph
RuntimeError: Method 'forward' is not defined.

是我之前的操作错误了吗?还是其他地方出现了问题，期待您的回复。
我将下载后的文件存放在

def _download(url: str, root: str = os.path.expanduser("/data2/gaoyuming/reforce_project/Vision-Language-Grasping-master/clip_model")):

**Comment by xukechun** [comment]
你好！可能这个有帮助：https://github.com/openai/CLIP/issues/408

**Comment by huamo555** [comment]
感谢您的帮助，问题已解决。
