### ISSUE TITLE
No cases/temp.txt

### ISSUE THREAD

**Issue by huamo555** [xukechun/Vision-Language-Grasping#11]
Thank you for your excellent work, I am having a problem running train.py, I don't seem to have cases/temp.txt, where can I find him please?

Traceback (most recent call last):
  File "train.py", line 145, in <module>
    reset = env.add_objects(warmup_num_obj, WORKSPACE_LIMITS) # 加入物体到工作台
  File "/data2/gaoyuming/reforce_project/Vision-Language-Grasping-master/Vision-Language-Grasping-master/environment_sim.py", line 454, in add_objects
    with open("cases/" + "temp.txt", "w") as out_file:
FileNotFoundError: [Errno 2] No such file or directory: 'cases/temp.txt'

**Comment by xukechun** [comment]
Hi, case/temp.txt is just a temporary file that records the configuration of the current scene. You can just build a blank .txt file initially.
