### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by szyzp** [xukechun/Vision-Language-Grasping#20]
```
Traceback (most recent call last):
  File "scripts/train.py", line 114, in <module>
    reset = env.add_objects(warmup_num_obj, WORKSPACE_LIMITS)
  File "/data/yzp/Vision-Language-Grasping/env/environment_sim.py", line 511, in add_objects
    body_id = pb.loadURDF(
pybullet.error: Cannot load URDF file.
Exception ignored in: <function Environment.__del__ at 0x7e1dbe5c8790>
Traceback (most recent call last):
  File "/data/yzp/Vision-Language-Grasping/env/environment_sim.py", line 425, in __del__
TypeError: 'NoneType' object is not callable
```
assets/simplified_objects和assets/unseen_objects已经存在，但URDF并未加载成功。（由于numpy.core.multiarray failed to import报错，将numpy升级为1.23.0版本，其余环境与安装要求一致）

**Comment by szyzp** [comment]
assets/simplified_objects下载时部分文件丢失，重新下载该文件夹，bug已解决。
