### ISSUE TITLE
RunTime ERROR

### ISSUE THREAD

**Issue by LemonQC** [xukechun/Vision-Language-Grasping#24]
When I run  python scripts/train.py

I got the following errors.

pybullet build time: Dec 20 2024 14:47:34
Traceback (most recent call last):
  File "scripts/train.py", line 7, in <module>
    import utils
  File "/data/users/lemon/VisionGrasping/scripts/utils.py", line 12, in <module>
    from env.constants import WORKSPACE_LIMITS, PIXEL_SIZE
ModuleNotFoundError: No module named 'env'

**Comment by xukechun** [comment]
Did you run `python setup.py develop`?
